#!/usr/bin/env perl

use v5.14;
use warnings;
use App::cat_v;

App::cat_v->new->run(splice @ARGV);

exit;

__END__

=encoding utf-8

=head1 NAME

cat-v - cat -v like tool

=head1 SYNOPSIS

cat-v [ options ] args ...

Command Options:

    -h --help          Print this message
    -v --version       Print version

=head1 VERSION

Version 1.01

=head1 DESCRIPTION

=head1 INSTALL

=head2 CPANMINUS

From CPAN archive:

    cpanm App::cat_v

From GIT repository:

    cpanm https://github.com/kaz-utashiro/App-cat_v.git

=head1 SEE ALSO

=head1 AUTHOR

Kazumasa Utashiro

=head1 LICENSE

© 2024 Kazumasa Utashiro.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
