name: test
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          [
            "5.38",
            "5.30",
            "5.24",
          ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install dependencies
#       run: cpanm -nq --installdeps --with-develop --with-recommends .
        run: cpanm -nq --installdeps --with-recommends .
      - name: Run test
        run: prove -lr t

